name: Theo Matussiere
theme: jekyll-theme-minimal
collections:
  misc:
    output: true
  nlp:
    output: true

markdown: kramdown
kramdown: 
  input: GFM
highlighter: rouge

permalink: /:category/:title.html

scholar:
  style: apa
  source: files
  bibliography: references.bib