name: Theo Matussiere
theme: jekyll-theme-minimal
collections:
  blog:
    output: true


markdown: kramdown
kramdown: 
  input: GFM
highlighter: rouge

permalink: /:category/:title.html

scholar:
  style: chicago
  source: files
  bibliography: references.bib