name: Theo Matussiere
theme: jekyll-theme-minimal
collections:
  misc:
    output: true

markdown: kramdown
kramdown: 
  input: GFM
highlighter: rouge

scholar:
  style: chicago
  source: _bibliography
  bibliography: references.bib